language: java
script: cd booking && ./gradlew clean build
deploy:
  provider: heroku
  api_key:
    secure: Y7WG4R1TWKROLUch73MEgjunMUOELewbuvgdb7Ga7r8N/eHaYYKVbgghz1bWnzkaFFbw7Pet86Rvpav/Ai563RapvJ0lLh0+6JgkRxrDHHpAmPmoQnr085/mvi/L2RYq9J0l5iVESEqQ/YCjTTcvub0z/Z65G98SPMUvCPwikEoc5WvC0VjO2b8yacGXc7UYEZ6afVi1xykHD78iYZ0s2k9Q5qDaqk6vBBsgrGHhUmZqotFThm/xLNby64ppSf8Y1bRS2QuPygVH2NjaSNiFaa/Vdw5QrkgU71WB2CvBx4YciWBd2F7SKrALOwrqQ2XFJY7+bUeTh6gJpDwprnnnZDFOKvhoyYZbq1MVkg0JzdO+mljGF6naTZW9K6Wg3EZGVLIVkp1HGiR7lIBV8lbKXXsrPLppDub+9Ee4APWl4myuYRgbi6Fry6Z/B+oK7e8zeS9wlEw8jGbXPUvy5jBnYyyctAj1etto2I5cn2KMdtx7VLC2vp3bdyXhmar4MdaZPx6pcNGYoaZqoiVDegU09YmBF6wODXAtv/LYEXmnGJwExg7v26uZtUYLy+1tgabCmQyG1T5cXb3rqiZ1uVgBgi+uQZiX3BLBkvBBGrkwYr7oUCazItkThVEzVUfZIBCLYXmRy/Grz6LFfZTdX2iUTvGXEwdpGKER3gptWO8ggtw=
