/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package booking

import io.javalin.Javalin
import java.lang.Integer.parseInt

fun main(args: Array<String>) {
    val port = parseInt(System.getenv("PORT"));

    bootstrapWebServer(Javalin.create()).start(port)
}

val bootstrapWebServer: (Javalin) -> Javalin =
        { javalinWebServer ->
            javalinWebServer.get("/hello/:name") { ctx ->
                ctx.result("Hello: " + ctx.pathParam("name"))
            }
            javalinWebServer
        }