/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package booking

import io.javalin.Javalin

fun main(args: Array<String>) {
    bootstrapWebServer(Javalin.create()).start()
}

val bootstrapWebServer: (Javalin) -> Javalin =
        { javalinWebServer ->
            javalinWebServer.get("/hello/:name") { ctx ->
                ctx.result("Hello: " + ctx.pathParam("name"))
            }
            javalinWebServer
        }