/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package booking

import com.mashape.unirest.http.Unirest
import io.javalin.Javalin
import org.assertj.core.api.Assertions.assertThat
import kotlin.test.Test

class AppTest {

    @Test
    fun `app should expose a hello world http get endpoint`() {
        val webServer = bootstrapWebServer(Javalin.create())
        webServer.start(1234)
        val response = Unirest.get("http://localhost:1234/hello/Wassel").asString()
        assertThat(response.status).isEqualTo(200)
        assertThat(response.body).isEqualTo("Hello: Wassel")
        webServer.stop()
    }
}
